services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SPRING_BOOT_API_URL=${SPRING_BOOT_API_URL}
    networks:
      - heapdog-network-dev

networks:
  heapdog-network-dev:
    external: true

