services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SSE_SERVER: ${NEXT_PUBLIC_SSE_SERVER}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    container_name: heapdog-frontend
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - PORT=5050
      - NODE_ENV=production
    networks:
      - heapdog-network
    restart: unless-stopped

networks:
  heapdog-network:
    external: true
