services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SSE_SERVER: ${NEXT_PUBLIC_SSE_SERVER}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    container_name: heapdog-frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - heapdog-network
    restart: unless-stopped

networks:
  heapdog-network:
    external: true
