/**
 * Extensive list of common math symbols and LaTeX expressions for problem setters.
 * Each entry: { label, latex, keywords } - keywords improve search.
 */
export const MATH_SYMBOLS = [
  // ─── Greek (lowercase) ─────────────────────────────────────────────────
  { label: "α alpha", latex: "\\alpha", keywords: "alpha greek" },
  { label: "β beta", latex: "\\beta", keywords: "beta greek" },
  { label: "γ gamma", latex: "\\gamma", keywords: "gamma greek" },
  { label: "δ delta", latex: "\\delta", keywords: "delta greek" },
  { label: "ε epsilon", latex: "\\epsilon", keywords: "epsilon greek" },
  { label: "ζ zeta", latex: "\\zeta", keywords: "zeta greek" },
  { label: "η eta", latex: "\\eta", keywords: "eta greek" },
  { label: "θ theta", latex: "\\theta", keywords: "theta greek" },
  { label: "ι iota", latex: "\\iota", keywords: "iota greek" },
  { label: "κ kappa", latex: "\\kappa", keywords: "kappa greek" },
  { label: "λ lambda", latex: "\\lambda", keywords: "lambda greek" },
  { label: "μ mu", latex: "\\mu", keywords: "mu greek" },
  { label: "ν nu", latex: "\\nu", keywords: "nu greek" },
  { label: "ξ xi", latex: "\\xi", keywords: "xi greek" },
  { label: "π pi", latex: "\\pi", keywords: "pi greek" },
  { label: "ρ rho", latex: "\\rho", keywords: "rho greek" },
  { label: "σ sigma", latex: "\\sigma", keywords: "sigma greek" },
  { label: "τ tau", latex: "\\tau", keywords: "tau greek" },
  { label: "φ phi", latex: "\\phi", keywords: "phi greek" },
  { label: "χ chi", latex: "\\chi", keywords: "chi greek" },
  { label: "ψ psi", latex: "\\psi", keywords: "psi greek" },
  { label: "ω omega", latex: "\\omega", keywords: "omega greek" },
  // Greek variants (curly/italic forms)
  { label: "ε varepsilon", latex: "\\varepsilon", keywords: "epsilon greek variant" },
  { label: "θ vartheta", latex: "\\vartheta", keywords: "theta greek variant" },
  { label: "ϱ varrho", latex: "\\varrho", keywords: "rho greek variant" },
  { label: "ς varsigma", latex: "\\varsigma", keywords: "sigma greek variant final" },
  { label: "φ varphi", latex: "\\varphi", keywords: "phi greek variant" },
  { label: "ϖ varpi", latex: "\\varpi", keywords: "pi greek variant" },
  // Greek uppercase
  { label: "Γ Gamma", latex: "\\Gamma", keywords: "gamma greek" },
  { label: "Δ Delta", latex: "\\Delta", keywords: "delta greek" },
  { label: "Θ Theta", latex: "\\Theta", keywords: "theta greek" },
  { label: "Λ Lambda", latex: "\\Lambda", keywords: "lambda greek" },
  { label: "Σ Sigma", latex: "\\Sigma", keywords: "sigma greek sum" },
  { label: "Π Pi", latex: "\\Pi", keywords: "pi greek product" },
  { label: "Φ Phi", latex: "\\Phi", keywords: "phi greek" },
  { label: "Ψ Psi", latex: "\\Psi", keywords: "psi greek" },
  { label: "Ω Omega", latex: "\\Omega", keywords: "omega greek" },

  // ─── Operators ────────────────────────────────────────────────────────
  { label: "± plus minus", latex: "\\pm", keywords: "plus minus" },
  { label: "∓ minus plus", latex: "\\mp", keywords: "minus plus" },
  { label: "× times", latex: "\\times", keywords: "times multiply" },
  { label: "÷ divide", latex: "\\div", keywords: "divide" },
  { label: "⋅ dot", latex: "\\cdot", keywords: "dot multiply" },
  { label: "∗ asterisk", latex: "\\ast", keywords: "asterisk" },
  { label: "⋆ star", latex: "\\star", keywords: "star" },
  { label: "∘ circle", latex: "\\circ", keywords: "circle composition" },
  { label: "⊕ oplus", latex: "\\oplus", keywords: "oplus xor" },
  { label: "⊗ otimes", latex: "\\otimes", keywords: "otimes tensor" },
  { label: "⊙ odot", latex: "\\odot", keywords: "odot" },
  { label: "⊖ ominus", latex: "\\ominus", keywords: "ominus minus" },
  { label: "⊘ oslash", latex: "\\oslash", keywords: "oslash" },
  { label: "∨ vee", latex: "\\vee", keywords: "vee or lor" },
  { label: "∧ wedge", latex: "\\wedge", keywords: "wedge and land" },
  { label: "∨ lor", latex: "\\lor", keywords: "lor or" },
  { label: "∧ land", latex: "\\land", keywords: "land and" },
  { label: "⋄ diamond", latex: "\\diamond", keywords: "diamond" },
  { label: "¬ neg", latex: "\\neg", keywords: "neg not" },
  { label: "∃ exists", latex: "\\exists", keywords: "exists" },
  { label: "∀ forall", latex: "\\forall", keywords: "forall" },
  { label: "∞ infinity", latex: "\\infty", keywords: "infinity lemniscate" },
  { label: "√ sqrt", latex: "\\sqrt{}", keywords: "sqrt root square" },
  { label: "∛ cube root", latex: "\\sqrt[3]{}", keywords: "cube root" },
  { label: "nth root", latex: "\\sqrt[n]{}", keywords: "root" },

  // ─── Relations ────────────────────────────────────────────────────────
  { label: "= equals", latex: "=", keywords: "equals" },
  { label: "≠ not equals", latex: "\\neq", keywords: "not equals ne neq" },
  { label: "≈ approx", latex: "\\approx", keywords: "approx approximately" },
  { label: "≡ equiv", latex: "\\equiv", keywords: "equiv congruent" },
  { label: "≤ leq", latex: "\\leq", keywords: "leq less equal" },
  { label: "≥ geq", latex: "\\geq", keywords: "geq greater equal" },
  { label: "< less", latex: "<", keywords: "less" },
  { label: "> greater", latex: ">", keywords: "greater" },
  { label: "≪ ll", latex: "\\ll", keywords: "much less" },
  { label: "≫ gg", latex: "\\gg", keywords: "much greater" },
  { label: "≲ lesssim", latex: "\\lesssim", keywords: "lesssim" },
  { label: "≳ gtrsim", latex: "\\gtrsim", keywords: "gtrsim" },
  { label: "≶ lessgtr", latex: "\\lessgtr", keywords: "lessgtr" },
  { label: "≷ gtrless", latex: "\\gtrless", keywords: "gtrless" },
  { label: "∼ sim", latex: "\\sim", keywords: "sim similar" },
  { label: "≃ simeq", latex: "\\simeq", keywords: "simeq" },
  { label: "≅ cong", latex: "\\cong", keywords: "cong congruent" },
  { label: "∝ proportional", latex: "\\propto", keywords: "proportional" },
  { label: "∣ divides", latex: "\\mid", keywords: "divides" },
  { label: "∤ not divides", latex: "\\nmid", keywords: "not divides" },
  { label: "∥ parallel", latex: "\\parallel", keywords: "parallel" },
  { label: "∦ nparallel", latex: "\\nparallel", keywords: "nparallel not parallel" },
  { label: "⊥ perp", latex: "\\perp", keywords: "perp perpendicular" },

  // ─── Set theory ───────────────────────────────────────────────────────
  { label: "∈ in", latex: "\\in", keywords: "in element belongs" },
  { label: "∉ not in", latex: "\\notin", keywords: "not in not element not belongs" },
  { label: "∋ ni", latex: "\\ni", keywords: "ni contains" },
  { label: "∪ union", latex: "\\cup", keywords: "union" },
  { label: "∩ cap", latex: "\\cap", keywords: "cap intersection" },
  { label: "⊆ subseteq", latex: "\\subseteq", keywords: "subseteq subset" },
  { label: "⊇ supseteq", latex: "\\supseteq", keywords: "supseteq superset" },
  { label: "⊂ subset", latex: "\\subset", keywords: "subset" },
  { label: "⊃ supset", latex: "\\supset", keywords: "supset" },
  { label: "⊊ subsetneq", latex: "\\subsetneq", keywords: "subsetneq proper subset" },
  { label: "⊋ supsetneq", latex: "\\supsetneq", keywords: "supsetneq proper superset" },
  { label: "⊑ sqsubseteq", latex: "\\sqsubseteq", keywords: "sqsubseteq square subset" },
  { label: "⊒ sqsupseteq", latex: "\\sqsupseteq", keywords: "sqsupseteq square superset" },
  { label: "⊔ sqcup", latex: "\\sqcup", keywords: "sqcup disjoint union" },
  { label: "⊓ sqcap", latex: "\\sqcap", keywords: "sqcap" },
  { label: "∅ emptyset", latex: "\\emptyset", keywords: "emptyset empty" },
  { label: "ℕ naturals", latex: "\\mathbb{N}", keywords: "naturals natural" },
  { label: "ℤ integers", latex: "\\mathbb{Z}", keywords: "integers integer" },
  { label: "ℚ rationals", latex: "\\mathbb{Q}", keywords: "rationals rational" },
  { label: "ℝ reals", latex: "\\mathbb{R}", keywords: "reals real" },
  { label: "ℂ complex", latex: "\\mathbb{C}", keywords: "complex" },
  { label: "ℙ probability", latex: "\\mathbb{P}", keywords: "probability P" },
  { label: "𝔼 expectation", latex: "\\mathbb{E}", keywords: "expectation E expected" },

  // ─── Calculus & sums ─────────────────────────────────────────────────
  { label: "∑ sum", latex: "\\sum", keywords: "sum summation" },
  { label: "∑ with limits", latex: "\\sum_{i=1}^{n}", keywords: "sum limits" },
  { label: "∏ product", latex: "\\prod", keywords: "product" },
  { label: "∏ with limits", latex: "\\prod_{i=1}^{n}", keywords: "product limits" },
  { label: "∐ coproduct", latex: "\\coprod", keywords: "coproduct" },
  { label: "⋀ bigwedge", latex: "\\bigwedge", keywords: "bigwedge" },
  { label: "⋁ bigvee", latex: "\\bigvee", keywords: "bigvee" },
  { label: "⨁ bigoplus", latex: "\\bigoplus", keywords: "bigoplus" },
  { label: "⨂ bigotimes", latex: "\\bigotimes", keywords: "bigotimes" },
  { label: "⨄ biguplus", latex: "\\biguplus", keywords: "biguplus disjoint" },
  { label: "⨆ bigsqcup", latex: "\\bigsqcup", keywords: "bigsqcup" },
  { label: "∫ integral", latex: "\\int", keywords: "integral" },
  { label: "∫ definite", latex: "\\int_{a}^{b}", keywords: "integral definite" },
  { label: "∬ double integral", latex: "\\iint", keywords: "double integral" },
  { label: "∭ triple integral", latex: "\\iiint", keywords: "triple integral" },
  { label: "∮ contour", latex: "\\oint", keywords: "contour integral" },
  { label: "∂ partial", latex: "\\partial", keywords: "partial derivative" },
  { label: "∇ nabla", latex: "\\nabla", keywords: "nabla gradient" },
  { label: "lim limit", latex: "\\lim", keywords: "limit" },
  { label: "lim x→∞", latex: "\\lim_{x \\to \\infty}", keywords: "limit infinity" },
  { label: "max", latex: "\\max", keywords: "max maximum" },
  { label: "min", latex: "\\min", keywords: "min minimum" },
  { label: "sup", latex: "\\sup", keywords: "sup supremum" },
  { label: "inf", latex: "\\inf", keywords: "inf infimum" },
  { label: "arg max", latex: "\\arg\\max", keywords: "argmax" },
  { label: "arg min", latex: "\\arg\\min", keywords: "argmin" },
  { label: "lim inf", latex: "\\liminf", keywords: "liminf limit inferior" },
  { label: "lim sup", latex: "\\limsup", keywords: "limsup limit superior" },
  { label: "det", latex: "\\det", keywords: "det determinant" },
  { label: "dim", latex: "\\dim", keywords: "dim dimension" },
  { label: "ker", latex: "\\ker", keywords: "ker kernel" },
  { label: "deg", latex: "\\deg", keywords: "deg degree" },
  { label: "hom", latex: "\\hom", keywords: "hom homomorphism" },
  { label: "rank", latex: "\\operatorname{rank}", keywords: "rank" },

  // ─── Arrows ──────────────────────────────────────────────────────────
  { label: "→ right arrow", latex: "\\to", keywords: "arrow right" },
  { label: "← left arrow", latex: "\\leftarrow", keywords: "arrow left" },
  { label: "↔ leftright", latex: "\\leftrightarrow", keywords: "arrow both" },
  { label: "⇒ implies", latex: "\\Rightarrow", keywords: "implies" },
  { label: "⇐ implied by", latex: "\\Leftarrow", keywords: "implied" },
  { label: "⇔ iff", latex: "\\Leftrightarrow", keywords: "iff equivalent" },
  { label: "↦ maps to", latex: "\\mapsto", keywords: "maps" },
  { label: "⟹ long right", latex: "\\Longrightarrow", keywords: "implies" },
  { label: "⟺ long iff", latex: "\\Longleftrightarrow", keywords: "iff" },
  { label: "↑ up", latex: "\\uparrow", keywords: "up" },
  { label: "↓ down", latex: "\\downarrow", keywords: "down" },
  { label: "↗ NE", latex: "\\nearrow", keywords: "northeast" },
  { label: "↘ SE", latex: "\\searrow", keywords: "southeast" },
  { label: "↙ SW", latex: "\\swarrow", keywords: "southwest" },
  { label: "↖ NW", latex: "\\nwarrow", keywords: "northwest" },

  // ─── Fractions & binomials ────────────────────────────────────────────
  { label: "a/b fraction", latex: "\\frac{a}{b}", keywords: "fraction" },
  { label: "1/2", latex: "\\frac{1}{2}", keywords: "half" },
  { label: "n choose k", latex: "\\binom{n}{k}", keywords: "binomial choose" },
  { label: "n over k", latex: "\\binom{n}{k}", keywords: "combination" },

  // ─── Accents & decorations ───────────────────────────────────────────
  { label: "x̄ bar", latex: "\\bar{x}", keywords: "bar overline" },
  { label: "x̂ hat", latex: "\\hat{x}", keywords: "hat" },
  { label: "x̃ tilde", latex: "\\tilde{x}", keywords: "tilde" },
  { label: "ẋ dot", latex: "\\dot{x}", keywords: "dot derivative" },
  { label: "ẍ ddot", latex: "\\ddot{x}", keywords: "ddot second derivative" },
  { label: "x⃗ vector", latex: "\\vec{x}", keywords: "vector" },
  { label: "x̄ overline", latex: "\\overline{x}", keywords: "overline" },
  { label: "x̲ underline", latex: "\\underline{x}", keywords: "underline" },
  { label: "x̂ widehat", latex: "\\widehat{x}", keywords: "widehat" },
  { label: "x̃ widetilde", latex: "\\widetilde{x}", keywords: "widetilde" },

  // ─── Brackets & delimiters ────────────────────────────────────────────
  { label: "( ) parentheses", latex: "()", keywords: "paren" },
  { label: "[ ] brackets", latex: "[]", keywords: "bracket" },
  { label: "{ } braces", latex: "\\{\\}", keywords: "brace" },
  { label: "⟨ ⟩ angle", latex: "\\langle \\rangle", keywords: "angle bracket" },
  { label: "| | absolute", latex: "|x|", keywords: "absolute value" },
  { label: "⌊ ⌋ floor", latex: "\\lfloor x \\rfloor", keywords: "floor" },
  { label: "⌈ ⌉ ceil", latex: "\\lceil x \\rceil", keywords: "ceil ceiling" },
  { label: "⎡ ⎤ matrix", latex: "\\left[ \\right]", keywords: "matrix" },
  { label: "( ) auto-size", latex: "\\left( \\right)", keywords: "auto size" },
  { label: "[ ] auto-size", latex: "\\left[ \\right]", keywords: "auto size" },

  // ─── Common expressions ──────────────────────────────────────────────
  { label: "x² squared", latex: "x^2", keywords: "squared power" },
  { label: "xⁿ power", latex: "x^n", keywords: "power exponent" },
  { label: "x⁻¹ inverse", latex: "x^{-1}", keywords: "inverse" },
  { label: "√x sqrt x", latex: "\\sqrt{x}", keywords: "sqrt" },
  { label: "n! factorial", latex: "n!", keywords: "factorial" },
  { label: "log", latex: "\\log", keywords: "log" },
  { label: "log₂", latex: "\\log_2", keywords: "log base 2 binary" },
  { label: "log₁₀", latex: "\\log_{10}", keywords: "log base 10" },
  { label: "ln", latex: "\\ln", keywords: "ln natural" },
  { label: "exp", latex: "\\exp", keywords: "exp exponential" },
  { label: "sin", latex: "\\sin", keywords: "sin sine" },
  { label: "cos", latex: "\\cos", keywords: "cos cosine" },
  { label: "tan", latex: "\\tan", keywords: "tan tangent" },
  { label: "cot", latex: "\\cot", keywords: "cot cotangent" },
  { label: "sec", latex: "\\sec", keywords: "sec secant" },
  { label: "csc", latex: "\\csc", keywords: "csc cosecant" },
  { label: "arcsin", latex: "\\arcsin", keywords: "arcsin" },
  { label: "arccos", latex: "\\arccos", keywords: "arccos" },
  { label: "arctan", latex: "\\arctan", keywords: "arctan" },
  { label: "sinh", latex: "\\sinh", keywords: "sinh hyperbolic" },
  { label: "cosh", latex: "\\cosh", keywords: "cosh hyperbolic" },
  { label: "tanh", latex: "\\tanh", keywords: "tanh hyperbolic" },
  { label: "gcd", latex: "\\gcd", keywords: "gcd" },
  { label: "lcm", latex: "\\operatorname{lcm}", keywords: "lcm" },
  { label: "mod", latex: "\\bmod", keywords: "mod modulo" },
  { label: "a ≡ b (mod n)", latex: "a \\equiv b \\pmod{n}", keywords: "modulo" },
  { label: "⌊x⌋ floor", latex: "\\lfloor x \\rfloor", keywords: "floor" },
  { label: "⌈x⌉ ceil", latex: "\\lceil x \\rceil", keywords: "ceil" },
  { label: "|x| abs", latex: "|x|", keywords: "absolute" },
  { label: "∥x∥ norm", latex: "\\|x\\|", keywords: "norm" },
  { label: "⌊x+½⌋ round", latex: "\\lfloor x + 0.5 \\rfloor", keywords: "round nearest" },

  // ─── Logic & proofs ────────────────────────────────────────────────────
  { label: "∴ therefore", latex: "\\therefore", keywords: "therefore" },
  { label: "∵ because", latex: "\\because", keywords: "because" },
  { label: "QED", latex: "\\square", keywords: "qed proof" },
  { label: "□ square", latex: "\\square", keywords: "square qed" },
  { label: "■ blacksquare", latex: "\\blacksquare", keywords: "blacksquare filled" },
  { label: "△ triangle", latex: "\\triangle", keywords: "triangle" },
  { label: "◀ triangleleft", latex: "\\triangleleft", keywords: "triangleleft" },
  { label: "▶ triangleright", latex: "\\triangleright", keywords: "triangleright" },
  { label: "∠ angle", latex: "\\angle", keywords: "angle" },
  { label: "° degree", latex: "^{\\circ}", keywords: "degree" },
  { label: "′ prime", latex: "\\prime", keywords: "prime" },

  // ─── Matrices & arrays ───────────────────────────────────────────────
  { label: "2×2 matrix", latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", keywords: "matrix" },
  { label: "cases", latex: "\\begin{cases} x & \\text{if } x>0 \\\\ -x & \\text{otherwise} \\end{cases}", keywords: "cases piecewise" },
  { label: "array", latex: "\\begin{array}{cc} a & b \\\\ c & d \\end{array}", keywords: "array" },
  { label: "align", latex: "\\begin{align} a &= b \\\\ c &= d \\end{align}", keywords: "align equation" },

  // ─── Text in math ─────────────────────────────────────────────────────
  { label: "text", latex: "\\text{}", keywords: "text" },
  { label: "textbf", latex: "\\textbf{}", keywords: "bold" },
  { label: "textit", latex: "\\textit{}", keywords: "italic" },
  { label: "mathrm", latex: "\\mathrm{}", keywords: "roman" },
  { label: "mathbb", latex: "\\mathbb{}", keywords: "blackboard" },
  { label: "mathcal", latex: "\\mathcal{}", keywords: "calligraphic" },
  { label: "mathtt", latex: "\\mathtt{}", keywords: "monospace" },

  // ─── Spacing ──────────────────────────────────────────────────────────
  { label: "quad space", latex: "\\quad", keywords: "space" },
  { label: "qquad space", latex: "\\qquad", keywords: "space" },
  { label: "thin space", latex: "\\,", keywords: "space" },
  { label: "medium space", latex: "\\:", keywords: "space" },

  // ─── Misc ────────────────────────────────────────────────────────────
  { label: "… dots", latex: "\\dots", keywords: "dots ellipsis" },
  { label: "… ldots", latex: "\\ldots", keywords: "ldots dots low" },
  { label: "⋯ cdots", latex: "\\cdots", keywords: "cdots dots center" },
  { label: "⋮ vdots", latex: "\\vdots", keywords: "dots vertical" },
  { label: "⋱ ddots", latex: "\\ddots", keywords: "dots diagonal" },
  { label: "• bullet", latex: "\\bullet", keywords: "bullet" },
  { label: "★ star", latex: "\\star", keywords: "star" },
  { label: "† dagger", latex: "\\dagger", keywords: "dagger" },
  { label: "‡ ddagger", latex: "\\ddagger", keywords: "double dagger" },
  { label: "ℵ aleph", latex: "\\aleph", keywords: "aleph cardinal" },
  { label: "ℏ hbar", latex: "\\hbar", keywords: "hbar planck" },
  { label: "ℓ ell", latex: "\\ell", keywords: "ell" },
  { label: "ℜ real part", latex: "\\Re", keywords: "real part" },
  { label: "ℑ imag part", latex: "\\Im", keywords: "imaginary part" },
  { label: "O big O", latex: "O(n)", keywords: "big o complexity" },
  { label: "Θ big Theta", latex: "\\Theta(n)", keywords: "big theta" },
  { label: "Ω big Omega", latex: "\\Omega(n)", keywords: "big omega" },
] as const
